
name: Web Update

on:
  repository_dispatch:
    types: [new_release]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build site
        run: mkdir output && cp src/* output/

      - name: Replace version in template
        env:
          LATEST_TAG: ${{ steps.latest_version.outputs.latest_tag }}
        run: |
          set -o errexit
          set -o pipefail

          releases_json=$(curl https://api.github.com/repos/dn-vm/dnvm/releases)
          latest_stable=$(echo "$releases_json" | jq -r '. | map(select(.prerelease == false)) | .[0].tag_name')
          latest_preview=$(echo "$releases_json" | jq -r '. | map(select(.prerelease == true)) | .[0].tag_name')
          echo "Latest stable: $latest_stable"
          echo "Latest preview: $latest_preview"
          sed -i'.bak' "s/__latestVersion__/${latest_stable:1}/g" ./output/*.template
          sed -i'.bak' "s/__latestPreview__/${latest_preview:1}/g" ./output/*.template

      - name: Move templates to final name
        run: mv ./output/install.sh.template ./output/install.sh &&
             mv ./output/install.ps1.template ./output/install.ps1 &&
             mv ./output/releases.json.template ./output/releases.json &&
             rm ./output/*.template.bak

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output