
name: Web Update

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get latest dnvm release
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: dn-vm
          repo: dnvm
      - name: Example of consumption of the output
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
        run: |
          echo "Version $LATEST was released at $LATEST_DATE"
      - name: Build site
        run: mkdir output && cp src/* output/
      - name: Replace version in template
        env:
          LATEST_TAG: ${{ steps.latest_version.outputs.latest_tag }}
        run: sed -i'.bak' 's/__latestVersion__/v0.2.4/' ./output/install.sh.template
      - name: Move template to final name
        run: mv ./output/install.sh.template ./output/install.sh && rm ./output/install.sh.template.bak
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output